#!/usr/bin/env bash
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

project="$1"

cd "$root_dir/$project" > /dev/null
if [[ x"$configuration" == x"Release" ]]; then
	npm run watch_release
else
	npm run watch_debug
fi