#!/usr/bin/env bash
#/ Usage: script/procs/service <service>
#/ Description: Launches the specified service, and follows its logs.
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

service=
while (( "$#" )); do
  key="$1"
  shift
  case "$key" in
    -\?|-h|--help)
        grep '^#/' <"$0" | cut -c4-
        exit
    ;;
    *)
        service="$key"
    ;;
  esac
done

if [ -z $service ]; then
    echo "You must specify a service to follow"
    exit 1
fi

if ! docker-compose ps --services --filter "status=running" | grep $service >/dev/null 2>&1; then
    echo "Starting $service…"
    docker-compose up --no-log-prefix $service
else
    echo "Attaching to $service…"
    docker-compose logs -f --no-log-prefix $service
fi