#!/usr/bin/env bash
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

if [ -z $configuration ]; then
  configuration=Debug
fi

if [ "$USE_DOTNET_WATCH" = "1" ]; then
    dotnet watch --project "$root_dir/src/AIDemo.Web/AIDemo.Web.csproj" run --configuration $configuration
else
    dotnet run --project "$root_dir/src/AIDemo.Web/AIDemo.Web.csproj" --configuration $configuration
fi