#!/usr/bin/env bash
#/ Usage: script/all [-D|--daemonize] [-w|--watch] [-l|--list] [-e|--except <service>] [<configuration>]
#/ Description: Launches everything!
#/ Options:
#/   -D|--daemonize         Launch overmind as a daemon
#/   -w|--watch             Launch the .NET apps under 'dotnet-watch'
#/   -e|--except <service>  Don't launch the specified service
#/   -l|--list              List all services
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

configuration=
list=false
watch=false
ignore=
overmind_args=()
while (( "$#" )); do
  key="$1"
  shift
  case "$key" in
    -l|--list)
        list=true
    ;;
    -w|--watch)
        watch=true
    ;;
    -D|--daemonize)
        overmind_args+=("--daemonize")
    ;;
    -e|--except)
        if [ -z $ignore ]; then
            ignore=$1
        else
            ignore="$ignore,$1"
        fi
        shift
    ;;
    -\?|-h|--help)
      grep '^#/' <"$0" | cut -c4-
      exit
    ;;
    *)
      if [ -z $configuration ]; then
        configuration=$key
      fi
    ;;
  esac
done

if $list; then
    cat Procfile
    exit 0
fi

if [ -z $configuration ]; then
  configuration=Debug
fi

if $watch; then
    export USE_DOTNET_WATCH=1
fi

if type overmind >/dev/null 2>&1; then
    OVERMIND_IGNORED_PROCESSES=$ignore overmind start ${overmind_args[@]} --procfile "$root_dir/Procfile"
elif type hivemind >/dev/null 2>&1; then
    if [ -n "$ignore" ]; then
        echo "The '-e' option only works with overmind :("
        exit 1
    fi
    hivemind "$root_dir/Procfile"
else
    echo "script/all requires overmind or hivemind"
    echo "Install one of them with brew! (I recommend overmind)"
    exit 1
fi