#!/usr/bin/env bash
#/ Usage: script/build [<configuration>]
#/ Description: Builds AIDemo.Web
#/ Arguments:
#/   <configuration> - The configuration to build. Defaults to Debug.
source ./script/helpers/_utils.sh
set_source_and_root_dir

configuration=
while (( "$#" )); do
  key="$1"
  shift
  case "$key" in
    -\?|-h|--help)
      grep '^#/' <"$0" | cut -c4-
      exit
    ;;
    *)
      if [[ ! $configuration ]]; then
        configuration=$key
      fi
  esac
done

if [ -z $configuration ]; then
    configuration=Debug
fi

if ! type npm >/dev/null 2>&1; then
  fatal "npm is required to run this script. Have you run 'script/bootstrap'?"
fi

if ! type dotnet >/dev/null 2>&1; then
  fatal "dotnet is required to run this script. Have you run 'script/bootstrap'?"
fi

echo "Building AIDemo.sln for $configuration"
dotnet restore AIDemo.sln
dotnet build AIDemo.sln --no-restore -c $configuration --nologo

cd "$root_dir/src/AIDemo.Web" > /dev/null
npm install
npm rebuild node-sass
if [[ x"$configuration" == x"Release" ]]; then
    npm run release
else
    npm run debug
fi
