#!/usr/bin/env bash
#/ Usage: script/fmt [-c|--check]
#/ Description: Runs all formatters on the codebase.
#/ Options:
#/   -c, --check - Run in check mode. Will return a non-zero exit code if anything needs reformatting.
source ./script/helpers/_utils.sh
set_source_and_root_dir

SOLUTION_FILE="AIDemo.sln"
PROJECT_DIR="./src/AIDemo.Web"

check=false

while (( "$#" )); do
    key="$1"
    shift
    case "$key" in
        -c|--check)
            check=true
            ;;
        -\?|-h|--help)
            grep '^#/' <"$0" | cut -c4-
            exit
        ;;
    esac
done

if $check; then
    echo "Running in check mode: Will return a non-zero exit code if anything needs reformatting."
else
    echo "Running in reformat mode: Will automatically reformat files if they need reformatting."
fi

success=true

if type dotnet >/dev/null 2>&1; then
    dotnet_args=("--exclude=$PROJECT_DIR/Migrations")
    if $check; then
        dotnet_args+=("--verify-no-changes")
    fi
    echo "Running .NET Formatters..."

    # Run just 'whitespace' and 'style' formatters, not 'analyzer' formatters!
    if ! dotnet format whitespace "$SOLUTION_FILE" "${dotnet_args[@]}"; then
        success=false
    fi
    if ! dotnet format style "$SOLUTION_FILE" "${dotnet_args[@]}"; then
        success=false
    fi
elif $check; then
    echo ".NET CLI is not installed!" 1>&2
    exit 1
fi

if type npm >/dev/null 2>&1; then
    if $check; then
        npm_command="lint"
    else
        npm_command="lint:fix"
    fi

    echo "Running ECMAScript/TypeScript Formatters..."

    cd "$PROJECT_DIR"
    npm ci
    if ! npm run "$npm_command"; then
        success=false
    fi
elif $check; then
    echo "NPM is not installed!" 1>&2
    exit 1
fi

if $success; then
    echo "You're all good!"
else
    echo "Formatting is no good! Run 'script/fmt' to fix" 1>&2
    exit 1
fi