#!/usr/bin/env bash
#/ Usage: script/server [<configuration>]
#/ Description: Launches the AIDemo.Web Server
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

configuration=
while (( "$#" )); do
  key="$1"
  shift
  case "$key" in
    -\?|-h|--help)
      grep '^#/' <"$0" | cut -c4-
      exit
    ;;
    *)
      if [ -z $configuration ]; then
        configuration=$key
      fi
    ;;
  esac
done

if type overmind >/dev/null 2>&1; then
  overmind start --procfile "$root_dir/Procfile" --processes web
elif type hivemind >/dev/null 2>&1; then
  hivemind --processes web "$root_dir/Procfile"
else
  script/procs/web
fi
