#!/usr/bin/env bash
#/ Usage: script/server [<configuration>]
#/ Description: Launches the AIDemo.AppHost project
source ./script/helpers/_utils.sh
set_source_and_root_dir

configuration=
while (( "$#" )); do
  key="$1"
  shift
  case "$key" in
    -\?|-h|--help)
      grep '^#/' <"$0" | cut -c4-
      exit
    ;;
    *)
      if [ -z $configuration ]; then
        configuration=$key
      fi
    ;;
  esac
done

pushd "$root_dir"

if [ -z $configuration ]; then
  configuration=Debug
fi

dotnet run --project "$root_dir/src/AIDemo.AppHost/AIDemo.AppHost.csproj" --configuration $configuration

popd