#!/usr/bin/env bash
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

dotnet user-secrets --project src/AIDemo.Web/AIDemo.Web.csproj "$@"