#!/usr/bin/env bash
#/ Usage: script/watch [<configuration>]
#/ Description: Launches the AIDemo.Web server in 'watch' mode (reloading them on any changes)
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

configuration=
while (( "$#" )); do
  key="$1"
  shift
  case "$key" in
    -\?|-h|--help)
      grep '^#/' <"$0" | cut -c4-
      exit
    ;;
    *)
      if [ -z $configuration ]; then
        configuration=$key
      fi
    ;;
  esac
done

if [ -z $configuration ]; then
  configuration=Debug
fi

cd "$root_dir"

script/watch-js &
dotnet watch --project "$root_dir/src/AIDemo.AppHost/AIDemo.AppHost.csproj" run --configuration $configuration &

function cleanup() {
	trap - SIGTERM && kill -- -$$
	popd
}

# When you absolutely, positively got to kill every process in the room, accept no substitutes
# https://stackoverflow.com/a/2173421
trap cleanup SIGINT SIGTERM EXIT
